archives_extensions:
  - tar.gz
  - zip
readme:
  - README.md
  - readme.md
  - README.mkd
  - readme.mkd
  - README.rst
  - readme.rst
  - README.html
  - readme.html
  - README.htm
  - readme.htm
  - README.txt
  - readme.txt
  - README
  - readme
  - INSTALL.md
  - install.md
  - INSTALL.mkd
  - install.mkd
  - INSTALL.rst
  - install.rst
  - INSTALL.html
  - install.html
  - INSTALL.htm
  - install.htm
  - INSTALL.txt
  - install.txt
  - INSTALL
  - install
licences:
  - LICENSE
  - LICENSE.md
  - LICENSE.txt
  - BSD-3-Clause-Clear
  - GPL-2.0
  - BSD-3-Clause
  -	BSD-2-Clause
  - MIT
  - MIT-LICENSE
changelog:
  - CHANGELOG.md

contributing:
  - CONTRIBUTING.md