table: 'users'
admin_prefix: '/'
user_home: '/home'
create_action: '/create'
columns:
  password: 'password'
  id: 'id'
  auth: 'username'
messages:
  welcome: 'Welcome'
  user_not_found: 'User was not found'
  password_no_match: 'Password not match'
  bye: 'Bye'
  not_unique: 'Username must be unique'
  table_not_found: 'The table was not found'
  reset_fail: 'The password has not been modified'
