table: 'users'
admin_prefix: '/admin'
user_home: '/home'
create_action: '/create'
by: 'username'
messages:
  welcome: 'Welcome'
  user_not_found: 'User was not found'
  password_no_match: 'Password not match'
  account_removed_successfully: 'Your account has been successfully deleted'
  account_removed_fail: 'Sorry your account has not been removed'
  bye: 'Bye'
  not_unique: 'Username must be unique'
  table_not_found: 'The table was not found'
  reset_fail: 'The password has not been modified'