table: 'users'
admin_prefix: '/admin'
user_home: '/home'
create_action: '/create'
columns:
  password: 'password'
  id: 'id'
  auth: 'id'
messages:
  welcome: 'Welcome'
  user_not_found: 'User was not found'
  password_no_match: 'Password not match'
  account_created_successfully: 'Your account has been successfully created'
  account_creation_fail: 'Sorry your account has not been created'
  bye: 'Bye'
  not_unique: 'Username must be unique'
  table_not_found: 'The table was not found'
  reset_fail: 'The password has not been modified'
