mysql-root-password-question: "Entrez le mot de passe de l'utilisateur root de MySQL "
pgsql-postgres-password-question: "Entrez le mot de passe de l'utilisateur postgres de PostgreSQL "
source-driver-to-convert-question: 'Quel est le driver qui contient la base de données à convertir ? '
destination-driver-question : 'Vers quel driver souhaitez vous migrer ? '
enter-source-base-name-message: 'Entrez le nom de la base à convertir '
enter-new-base-name-message: 'Entrez le nom de la nouvelle base de données souhaiter '
new-base-name-already-exist: 'La base de données %s existe déjà'
source-base-not-exist-message: "La base de données %s n'éxiste pas"
enter-new-username-message: 'Entrez le nom du proprietaire à creer pour la nouvelle base '
username-not-exist-message: "L'utilisateur %s n'éxiste pas"
username-already-exist-message: "L'utilisateur %s éxiste déjà"
the-new-username-password: 'Entrez le mot de passe de connexion du nouvel utilisateur '
create-the-new-configuration: 'Créer la nouvelle configuration ?'
new-base-name-creation-fail: 'La création de la base de données %s a échouer'
new-base-name-created-successfully: 'La base de données %s à été creer avec success'
new-username-creation-fail: "La création de l'utilisateur %s a échouer"
new-username-creation-success: "L'utilisateur %s à été créer avec succès"