created: 'The record has been created successfully'
no_created: 'The creation has fail'
updated: 'The record has been updated successfully'
no_updated: 'The record has not been updated'
deleted: 'The record has been deleted successfully'
no_deleted: 'The record has not been deleted'
