created: 'The record has been created successfully'
no_created: 'The creation has fail'
updated: 'The record has been updated successfully'
no_updated: 'The record has not been updated'
deleted: 'The record has been deleted successfully'
no_deleted: 'The record has not been deleted'
update_text: 'update'
create_text: 'create'
select_table_text: 'select a table'
edit_text: 'edit'
remove_text: 'remove'
edit_class: 'btn btn-outline-primary'
remove_class: 'btn btn-outline-danger'
truncated: 'The table has been empty successfully'
no_truncated: 'The table has not been altered'
sure: 'Are you sure you want to delete this item?'