class:
  submit: 'btn-success'
  reset:  'btn-danger'
  remove: 'btn-danger'
  button: 'btn-secondary'
  link:   'btn-primary'
  group:  'btn-secondary'
  checkbox: 'form-control'
  edit:   'btn btn-primary'
  delete : 'btn btn-danger'
textarea:
  col: 10
  row: 10
save: true
padding: 2
margin: 4
validate: false
large: true
small: false
pagination_step: 10