class:
  submit: 'btn btn-lg btn-info btn-block btn-login text-uppercase font-weight-bold mb-2'
  reset:  'btn-danger'
  remove: 'btn-danger'
  button: 'btn-secondary'
  link:   'btn-primary'
  group:  'btn-secondary'
  checkbox: 'form-control'
  edit:   'btn btn-primary'
  delete : 'btn btn-danger'
  table:  'table table-bordered table-hover'
textarea:
  col: 10
  row: 5
save: true
padding: 2
margin: 2
validate: false
large: true
small: false
pagination_step: 10
space: true