contribution_text: 'contributions'
authors_order_by: 'commits'

class:
  contributions: 'text-success'
  search: 'form-control-lg form-control mt-5 mb-5'
placeholders:
  search: 'search'
tables:
  users: 'users'

repositories:
  contributors: 'contributors'
  name: 'name'
  owner: 'owner'
  issues: 'issues'
  branches: 'branches'
  release: 'release'
  licence: 'Licence'