namespace: 'Testing'

GET:
  home:
     url: '/'
     call: 'Welcome@show'
  pagination:
    url: '/:x'
    call: 'Welcome@pagination'
  remove:
    url: '/remove/:table/:id'
    call: 'Welcome@remove'
  edit:
    url: '/edit/:table/:id'
    call: 'Welcome@edit'
POST:
  del:
    url: '/del'
    call: 'Welcome@del'
  update:
    url: '/update'
    call: 'Welcome@update'
  create:
    url: '/create'
    call: 'Welcome@create'