route-name-question: 'Quel est le nom de la nouvelle route ?'
route-name: 'Quel est le nom de la route ?'
route-name-to-delete: 'Quel est le nom de la route à supprimer ?'
change-name: 'Entrez le nouveau nom de la route'
change-method: 'Entrez la nouvelle method pour la route'
change-controller: 'Entrez le nouveau controlleur pour la route'
change-action: 'Entrez la nouvelle action pour la route'
change-url: 'Entrez la nouvelle url pour la route'
change-directory: 'Entrez le nouveau repertoire du controlleur'
route-name-already-taken: 'Le nom est déjà utilisé'
route-method-question: 'Quel method la route %s devrait utiliser ?'
route-url-question: "Quel est l'url pour la nouvelle route %s ?"
route-url-already-taken: "l'url %s est déjà utilisé"
route-controller-question: 'Quel est le controlleur relier a la route ?'
route-creation-again: 'Voulez vous créer une nouvelle route ?'
route-update-again: 'Voulez vous mettre a jour une nouvelle route ?'
remove-route-again: 'Voulez vous supprimer une autre route ?'
route-action-question: 'Quelle action du controlleur %s doit etre appeler ?'
route-name-not-exist: "La route %s n'éxiste pas"
route-action-not-exist: "Attention l'action %s n'as pas été trouvée pensez à la créer"
route-action-already-taken: "L'action %s est déjà utilisé par une autre route"
route-controller-directory-question: 'Quel est le nom du repertoire du controlleur ?'
route-controller-directory-not-exist: "Le dossier %s n'éxiste pas"
route-controller-not-exist: "Le controleur %s n'éxiste pas"
route-method-not-valid: "La méthode %s n'est pas supportée"
route-name-already-exist: 'La route %s éxiste déjà'
route-created: 'La route %s à été créer avec succès'
route-create-fail: 'La création de la route %s à échoué'
bye: 'Au revoir'
route-updated-successfully: 'La route %s à été mise a jour avec succès'
route-update-failed: 'La mise a jour de la route %s à échoué'
route-removed-successfully: 'La route %s à été supprimer avec succès'
route-removed-fail: 'La suppresion de la route %s à échoué'
no-routes-has-been-found: 'La table des routes est vide'
search: 'Que recherchez vous ? '
continue: 'Continuer ?'
base-not-exist: "La base de données qui doit contenir les routes n'éxiste pas"
base-removed-successfully: "La base de données à été supprimé avec succès"
base-removed-fail: "La suppresion de la base de données à échoué"
base-created-successfully: "La base de données à été créer avec success"
base-created-failed: "La création de la base de données à échoué"
controller-not-exist: "Le contrôleur %s n'éxiste pas"
directory-not-exist: "Le répertoire %s n'éxiste pas dans le dossier des contrôleurs"
action-not-exist: "L'action %s n'éxiste pas dans la class %s"
can-use-the-router: 'Les routes sont valides'
