namespace: 'Testing'

GET:
  home:
     url: '/'
     call: 'Welcome@show'

  remove:
    url: '/remove/:table/:id'
    call: 'Welcome@remove'
  edit:
    url: '/edit/:table/:id'
    call: 'Welcome@edit'
POST:
  del:
    url: '/del'
    call: 'Welcome@del'
