required: 'The %s argument is required'
digits: "The %s argument is not a digit"
unique: 'The %s value is not unique inside the %s table'
between: 'The %s argument must be between %d and %d'
max: 'The %s argument is superior to %d'
min: 'The %s argument is inferior to %d'
email: 'The %s email is not a valid email'
slug: 'The %s is not a slug'
snake: 'The %s is not a snake case string format'
camel: 'The %s is not a camel case string format'
array: 'The %s is not an array'
boolean: 'The %s is not an boolean'
image: 'The %s is not an image'
json: 'The %s is not a json'
string: 'The %s is not a string'
url: 'The %s is not an url'
float: 'The %s is not a float'
int: 'The %s is not a int'
mac: 'The %s is not a mac address'
ipv4: 'The %s is not a valid ipv4 address'
ipv6: 'The %s is not a valid ipv6 address'
domain: 'The %s is not a valid domain'