required: 'The %s argument is required'
digit: "The %s argument is not a digit"
unique: 'The %s value is not unique inside the %s table'
between: 'The %s argument must be between %d and %d'
max: 'The %s argument is superior to %d'
min: 'The %s argument is inferior to %d'
email: 'The %s email is not a valid email'