en:
  required: 'The %s field is required'
  empty: 'The %s field must not be empty'
  between: 'The %s field must be between %d and %d'
  email: 'The %s email is not valid'
  digits: 'The %s argument is not a number'
  alpha: 'The %s argument is not alpha'
  alphanumeric: 'The %s argument is not alphanumeric'
  boolean: 'The %s argument is not a boolean'
  lower: 'The %s field must be in lowercase'
  upper: 'The %s field must be in uppercase'
fr:
  required: 'Le champ %s est requis'
  empty: 'Le champ %s ne peux pas être vide'
  between: 'The %s field must be between %d and %d'
  email: 'The %s email is not valid'
  digits: 'The %s argument is not a number'
  alpha: 'The %s argument is not alpha'
  alphanumeric: 'The %s argument is not alphanumeric'
  boolean: 'The %s argument is not a boolean'
