en:
  required: 'The %s field is required'
  empty: 'The %s field must not be empty'
  between: 'The %s field must be between %d and %d'
  email: 'The %s email is not valid'
  digits: 'The %s argument is not a number'
  alpha: 'The %s argument is not alpha'
  alphanumeric: 'The %s argument is not alphanumeric'
  boolean: 'The %s argument is not a boolean'
  lower: 'The %s field must be in lowercase'
  upper: 'The %s field must be in uppercase'
fr:
  required: 'Le champ %s est requis'
  empty: 'Le %s ne peux pas être vide'
  between: 'Le %s doit être compris entre %d et %d'
  email: 'L\'email' n\'est pas valide'
  digits: 'L`\argument %s n\'est pas un nombre'
  alpha: 'L`\argument %s n\'est pas un alpha'
  alphanumeric: 'L`\argument %s n\'est pas alphanumeric'
  boolean: 'The %s argument n'est pas un booleen'