commit-success-message: 'Le commit a été enregistré avec succès'
commit-fail-message: 'La création du commit a échoué'
commit-message-prompt: 'Expliquer les changements'
start-tests-message: 'Exécution des tests'
tests-success-message: 'Félicitations aucune erreur trouvées'
confirm-send-message: 'Envoyer les modifications ?'
confirm-send-message-default-value: true
send-message: 'Mise à jour des référentiels'
send-message-to: 'Mise à jour du référentiel héberger à %s'
remote-updated-success-message: 'Le référentiel a été mis à jour avec succès'
remote-updated-fail-message: 'Vérifier que vous avez les droits et que le référentiel existe'
all-remotes-updated-success-message: 'Tous les référentiels ont été mis à jour'
end-of-remotes-message: 'Fin des référentiels'
remotes-empty: 'Aucun référentiel trouvés'
confirm-add-message: 'Ajouter les modifications ?'
add-success-message: 'Les modifications ont été ajoutées avec succès'
add-fail-message: "L'ajout des modifications a échoué"
type-filename-prompt: "Entrez le nom d'un fichier "
no-files-found-message: "Aucun fichier as été trouvés"
continue-message: 'Continuer ?'
bye-message: 'Au revoir'
continue-message-default-value: true
completions: []

